export const UserInfo = '/user/info'
export const TeamInfo = '/team/info'
export const ScheduleInfo = '/schedule/info'
export const ScheduleRandom = '/schedule/random'
export const SettingInfo = '/setting/info'
